[package]
name = "ycmark"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
pulldown-cmark = { version = "0.13.0", features = ["html"] }
yaml-rust2 = "0.10.3"
